import { AuditResult, RecentExploration } from '../src/types/audit.js';

export interface PresetWebsite {
  id: string;
  name: string;
  url: string;
  category: string;
  description: string;
  presetResult: AuditResult;
}

export const SUGGESTED_EXPLORATIONS: RecentExploration[] = [
  {
    url: 'https://hotel-colonial-suites-demo.example.com',
    title: 'Hotel Colonial & Suites | Reservas y Tarifas',
    score: 32,
    ratingLevel: 'Crítico',
    scannedAt: 'Hace 5 minutos',
  },
  {
    url: 'https://odontosalud-demo.example.com',
    title: 'Clínica OdontoSalud - Odontología Integral y Urgencias',
    score: 56,
    ratingLevel: 'Advertencia',
    scannedAt: 'Hace 18 minutos',
  },
  {
    url: 'https://acrobatix-cloud.example.com',
    title: 'Acrobatix Cloud OS - Enterprise Cloud Platform',
    score: 86,
    ratingLevel: 'Bueno',
    scannedAt: 'Hace 42 minutos',
  },
  {
    url: 'https://ferreteria-elmartillo.example.com',
    title: 'Ferretería Industrial El Martillo - Catálogo y Contacto',
    score: 28,
    ratingLevel: 'Crítico',
    scannedAt: 'Hace 1 hora',
  },
  {
    url: 'https://novabistro-restaurante.example.com',
    title: 'NovaBistro - Gastronomía Fusión & Menú Digital',
    score: 64,
    ratingLevel: 'Advertencia',
    scannedAt: 'Hace 2 horas',
  },
];

export const PRESET_WEBSITES: PresetWebsite[] = [
  {
    id: 'legacy_hotel',
    name: 'Hotel Colonial & Suites',
    url: 'https://hotel-colonial-suites-demo.example.com',
    category: 'Hotelería / Turismo',
    description: 'Sitio sin viewport móvil, maquetado con tablas HTML, jQuery 1.8.2 vulnerable, certificado SSL caducado, sin WhatsApp y TTFB de 1840ms.',
    presetResult: {
      url: 'https://hotel-colonial-suites-demo.example.com',
      pageTitle: 'Hotel Colonial & Suites | Reservas, Tarifas y Alojamiento',
      scannedAt: new Date().toISOString(),
      status: 'success',
      auditDurationMs: 1420,
      totalForks: 38,
      scores: {
        overall: 32,
        performance: 28,
        tech: 22,
        cro: 35,
        security: 45,
        ratingLevel: 'Crítico',
        colorHex: '#F85149',
      },
      issues: [
        {
          id: 'ISS-001',
          title: 'Ausencia crítica de Viewport Responsive',
          category: 'tech',
          severity: 'critical',
          impactScore: 25,
          description: 'No existe etiqueta <meta name="viewport">. El sitio fuerza zoom manual en smartphones, provocando un 78% de rebote en móviles según estándares Google.',
          evidence: '<head> carece de meta viewport tag',
          recommendation: 'Reconstruir el layout con CSS Flexbox/Grid responsive mobile-first y declarar viewport estándar.',
        },
        {
          id: 'ISS-002',
          title: 'Maquetación obsoleta basada en <table> anidadas',
          category: 'tech',
          severity: 'critical',
          impactScore: 20,
          description: 'Se detectaron 14 tablas utilizadas para estructura visual y columnas, bloqueando el renderizado progresivo del navegador.',
          evidence: '14 elementos <table width="100%" cellpadding="0"> encontrados como contenedor',
          recommendation: 'Sustituir tablas estructurales por maquetación semántica moderna HTML5.',
        },
        {
          id: 'ISS-003',
          title: 'Librería jQuery 1.8.2 obsoleta con vulnerabilidades conocidas',
          category: 'tech',
          severity: 'critical',
          impactScore: 18,
          description: 'Versión lanzada en 2012 con vulnerabilidades CVE documentadas (Cross-Site Scripting CVE-2015-9251 y CVE-2019-11358).',
          evidence: 'script src="/js/jquery-1.8.2.min.js"',
          recommendation: 'Eliminar jQuery y migrar a JavaScript Vanilla ES2024 o framework moderno React/Vite.',
        },
        {
          id: 'ISS-004',
          title: 'Tiempo de primer byte (TTFB) crítico: 1,840 ms',
          category: 'performance',
          severity: 'critical',
          impactScore: 18,
          description: 'El servidor tarda casi 2 segundos solo en devolver el primer byte HTML, triplicando el límite recomendado por Google (600ms).',
          evidence: 'TTFB medido: 1,840ms en conexión directa',
          recommendation: 'Implementar servidor Edge/CDN (Cloudflare), compresión Gzip/Brotli y optimización de base de datos.',
        },
        {
          id: 'ISS-005',
          title: 'Cero presencia de canal conversacional de WhatsApp',
          category: 'cro',
          severity: 'critical',
          impactScore: 15,
          description: 'En el sector turismo el 62% de reservas espontáneas se cierran por chat directo. No se detectó botón, widget ni enlace wa.me.',
          evidence: '0 enlaces o widgets wa.me / api.whatsapp.com encontrados',
          recommendation: 'Integrar botón flotante permanente de WhatsApp con mensaje inicial predeterminado.',
        },
      ],
      performance: {
        ttfbMs: 1840,
        totalLoadTimeMs: 4200,
        htmlSizeBytes: 184000,
        estimatedAssetCount: 34,
        scriptsCount: 8,
        stylesCount: 6,
        imagesCount: 16,
        iframesCount: 2,
        domNodesTotal: 1840,
        maxDomDepth: 18,
        compressionType: 'none',
        sslEnabled: true,
        hstsEnabled: false,
        mixedContentDetected: true,
        uncompressedImagesCount: 12,
        blockingScriptsCount: 7,
        networkInfrastructure: {
          ipAddresses: ['198.51.100.42'],
          ipv4: ['198.51.100.42'],
          ipv6: [],
          hostname: 'hotel-colonial-suites-demo.example.com',
          detectedServer: 'Apache/2.2.22 (Debian Linux)',
          hostingProviderOrCdn: 'Hostinger VPS Legacy (Sin CDN ni Cloudflare)',
          dnsLookupTimeMs: 142,
        },
      },
      techStack: {
        detected: [
          {
            name: 'jQuery',
            category: 'JavaScript Library',
            version: '1.8.2',
            description: 'Biblioteca clásica de JavaScript que simplifica el recorrido y manipulación del DOM.',
            website: 'https://jquery.com',
            isObsolete: true,
            riskNote: 'Vulnerabilidades XSS CVE-2015-9251 y CVE-2019-11358 activas.',
          },
          {
            name: 'Apache HTTP Server',
            category: 'Web Server',
            version: '2.2',
            description: 'Servidor web HTTP de código abierto desarrollado por Apache Software Foundation.',
            website: 'https://httpd.apache.org',
            isObsolete: true,
            riskNote: 'Rama 2.2 sin soporte oficial.',
          },
        ],
        hasResponsiveViewport: false,
        viewportContent: undefined,
        usesTablesForLayout: true,
        tableLayoutCount: 14,
        usesIframesForLayout: true,
        iframeCount: 2,
        legacyJqueryDetected: true,
        jqueryVersion: '1.8.2',
        deprecatedHtmlTags: ['<font>', '<center>', '<table cellpadding>'],
        htmlDoctype: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">',
      },
      securitySummary: {
        observatoryScore: 'F',
        missingHeaders: [
          'Strict-Transport-Security (HSTS)',
          'Content-Security-Policy (CSP)',
          'X-Frame-Options',
          'X-Content-Type-Options',
        ],
        sslCertificate: {
          issuer: 'cPanel, Inc. Certification Authority',
          subject: 'hotel-colonial-suites-demo.example.com',
          validFrom: '2023-01-15T00:00:00.000Z',
          validTo: '2024-04-15T23:59:59.000Z',
          daysRemaining: -168,
          signatureAlgorithm: 'sha256WithRSAEncryption',
          protocol: 'TLSv1.2 (TLS 1.3 no soportado en Apache 2.2)',
          cipher: 'ECDHE-RSA-AES256-SHA384',
          isExpired: true,
          isValid: false,
          serialNumber: '3A:8F:29:41:00:99:C1',
        },
        vulnerabilities: [
          {
            id: 'CVE-2015-9251',
            source: 'OSV.dev',
            name: 'CVE-2015-9251 (jQuery 1.8.2)',
            component: 'jQuery v1.8.2',
            severity: 'Crítico',
            summary: 'Cross-Site Scripting (XSS) mediante parseHTML con fuentes no confiables.',
            recommendation: 'Eliminar jQuery legacy y migrar a Vanilla JS.',
          },
          {
            id: 'CVE-2019-11358',
            source: 'OSV.dev',
            name: 'CVE-2019-11358 (jQuery Prototype Pollution)',
            component: 'jQuery v1.8.2',
            severity: 'Medio',
            summary: 'Contaminación de Object.prototype en llamadas a $.extend().',
            recommendation: 'Actualizar a jQuery moderno o migrar.',
          },
          {
            id: 'SEC-HDR-HSTS',
            source: 'Mozilla Observatory',
            name: 'Cabecera HSTS ausente',
            component: 'HTTP Response Headers',
            severity: 'Medio',
            summary: 'No se fuerza el uso estricto de HTTPS en todos los subdominios.',
            recommendation: 'Habilitar Strict-Transport-Security en el servidor.',
          },
          {
            id: 'SEC-HDR-CSP',
            source: 'Mozilla Observatory',
            name: 'Content-Security-Policy omitida',
            component: 'HTTP Response Headers',
            severity: 'Medio',
            summary: 'Sin política de orígenes de recursos para mitigar inyecciones XSS.',
            recommendation: 'Definir cabecera CSP estricta.',
          },
        ],
        totalVulnCount: 4,
      },
      cro: {
        ctaCount: 2,
        ctas: [
          { text: 'Ver más', href: '#', tagName: 'A', isHighIntent: false },
          { text: 'Enviar', href: '#', tagName: 'INPUT', isHighIntent: false },
        ],
        hasWhatsApp: false,
        whatsAppLinks: [],
        whatsAppDetails: {
          detected: false,
          type: 'none',
          hasPredefinedMessage: false,
          diagnosisNote: 'No se detectaron botones de WhatsApp, widgets flotantes ni integraciones de chat activas en el código HTML, scripts ni estilos.',
        },
        hasPhoneLink: false,
        phoneLinks: [],
        hasContactForm: true,
        formCount: 1,
        formFieldIssues: [
          "El formulario '#form_contacto' contiene 3 campos <input> ('nombre', 'correo', 'comentario') sin etiquetas <label> explícitas ni atributo 'aria-label', afectando la accesibilidad en lectores de pantalla y reduciendo la tasa de completado.",
        ],
        headingHierarchy: [
          { tag: 'h1', text: 'Bienvenidos al Hotel Colonial', level: 1 },
          { tag: 'h1', text: 'Nuestras Habitaciones', level: 1 },
          { tag: 'h1', text: 'Tarifas 2018', level: 1 },
          { tag: 'h4', text: 'Amenidades generales', level: 4 },
        ],
        h1Count: 3,
        h1Texts: ['Bienvenidos al Hotel Colonial', 'Nuestras Habitaciones', 'Tarifas 2018'],
        hasSingleH1: false,
        headingIssues: [
          'Existe más de una etiqueta <h1> principal en la página (se detectaron 3 etiquetas)',
          'Salto jerárquico no semántico: De <h1> ("Tarifas 2018") salta directamente a <h4> ("Amenidades generales") omitiendo <h2> y <h3>',
        ],
        croFindings: [
          'Existe más de una etiqueta <h1> principal en la página (se detectaron 3 etiquetas: "Bienvenidos al Hotel Colonial", "Nuestras Habitaciones", "Tarifas 2018"), diluyendo la relevancia semántica para Google.',
          'Salto jerárquico no semántico: De <h1> ("Tarifas 2018") salta directamente a <h4> ("Amenidades generales") omitiendo <h2> y <h3>.',
          'No se detectaron botones de WhatsApp, widgets flotantes ni integraciones de chat activas en el código HTML, scripts ni estilos.',
          "El formulario '#form_contacto' contiene 3 campos <input> ('nombre', 'correo', 'comentario') sin etiquetas <label> explícitas ni atributo 'aria-label', impidiendo la accesibilidad y el autocompletado en móviles.",
          'Llamadas a la acción (CTAs) deficientes: Únicamente 2 botones detectados ("Ver más", "Enviar") sin texto de beneficio comercial específico.',
        ],
        wordCount: 320,
        totalImages: 16,
        imagesMissingAlt: 11,
        hasSocialProof: false,
        hasLegalPrivacyLink: false,
      },
      quote: {
        tierId: 'redesign_pro',
        tierName: 'Rediseño Completo Web Pro & Modernización',
        tagline: 'Modernización arquitectónica completa eliminando deuda técnica de 10+ años y activando canal directo de reservas.',
        summary: 'Reconstrucción total desde cero en arquitectura React / Vite ultra liviana, diseño responsive mobile-first para smartphones, canal directo de WhatsApp, aceleración Core Web Vitals (< 800ms) y formulario de cotización interactivo.',
        estimatedDeliveryDays: 12,
        estimatedConversionUplift: '+120% a +240% en consultas y reservas',
        totalEstimatedHours: 79,
        lineItems: [
          {
            id: 'mod_core_arch',
            title: 'Reingeniería Arquitectónica React/Vite Mobile-First',
            category: 'core',
            triggerReason: 'Sitio maquetado con tablas HTML y sin viewport responsive',
            estimatedHours: 28,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Tu página actual se ve microscópica en celulares y utiliza tablas del año 2000.',
            clientBenefit: 'Los usuarios de móviles podrán navegar y reservar con total fluidez.',
          },
          {
            id: 'mod_whatsapp_funnel',
            title: 'Canal de Conversión Inmediata WhatsApp con Mensajes Inteligentes',
            category: 'cro',
            triggerReason: 'Ausencia total de enlace directo a chat wa.me en sector turismo',
            estimatedHours: 8,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'El 65% de turistas cierran reservas espontáneas por chat directo.',
            clientBenefit: 'Botón flotante permanente para responder consultas al instante.',
          },
          {
            id: 'mod_speed_vitals',
            title: 'Optimización Core Web Vitals (WebP/AVIF + Compresión Brotli + TTFB < 600ms)',
            category: 'perf',
            triggerReason: 'TTFB crítico de 1,840ms y 4.2MB de imágenes sin optimizar',
            estimatedHours: 12,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Tu servidor actual tarda casi 2 segundos solo en empezar a responder.',
            clientBenefit: 'Carga instantánea que reduce al mínimo el abandono de usuarios.',
          },
          {
            id: 'mod_interactive_form',
            title: 'Cotizador Interactivo de Habitaciones en 3 Pasos con Webhook',
            category: 'cro',
            triggerReason: 'Formulario tradicional php monolítico con alta tasa de abandono',
            estimatedHours: 14,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Formularios anticuados que provocan frustración en los clientes.',
            clientBenefit: 'Captura ágil de datos y notificación inmediata al equipo comercial.',
          },
          {
            id: 'mod_seo_headings',
            title: 'Reestructuración Semántica SEO y Arquitectura de Encabezados H1-H3',
            category: 'seo',
            triggerReason: 'Múltiples H1 conflictivos y 11 imágenes sin texto descriptivo ALT',
            estimatedHours: 8,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Confusión de titulares que afecta el posicionamiento en Google.',
            clientBenefit: 'Mejor posición en búsquedas turísticas sin pagar publicidad.',
          },
          {
            id: 'mod_security_hardening',
            title: 'Hardening de Seguridad, Erradicación de jQuery 1.8.2 y HSTS SSL',
            category: 'core',
            triggerReason: 'Vulnerabilidades XSS registradas y certificado SSL caducado',
            estimatedHours: 9,
            selected: true,
            isCore: false,
            plainWhyNeeded: 'Librerías obsoletas con fallas de seguridad conocidas públicamente.',
            clientBenefit: 'Blindaje completo contra inyecciones de código y ciberataques.',
          },
        ],
        actionRoadmap: [
          { phase: 'Fase 1', title: 'Diseño UX/UI & Prototipo Wireframe Móvil', duration: 'Días 1 - 3', tasks: ['Propuesta visual moderna', 'Estructura semántica', 'Definición de copies y CTAs persuasivos'] },
          { phase: 'Fase 2', title: 'Desarrollo Frontend React + Componentes', duration: 'Días 4 - 8', tasks: ['Maquetación responsive Tailwind', 'Integración WhatsApp flotante', 'Cotizador en 3 pasos'] },
          { phase: 'Fase 3', title: 'Aceleración Vitals, SEO & Go-Live', duration: 'Días 9 - 12', tasks: ['Conversión de imágenes a WebP', 'Configuración CDN Edge', 'Testing cross-browser y entrega final'] },
        ],
      },
      subagents: [
        {
          id: 'agent_orchestrator',
          name: 'ORCHESTRATOR_AGENT',
          role: 'Controlador Maestro de Auditoría y Detección de Protocolos',
          status: 'completed',
          executionTimeMs: 1420,
          forksCount: 4,
          findingsCount: 4,
          tasksCompleted: [
            'Handshake SSL/TLS verificado',
            'Título extraído: "Hotel Colonial & Suites | Reservas, Tarifas y Alojamiento"',
            'Auditoría silenciosa de seguridad (OSV.dev + Mozilla Observatory)',
          ],
          telemetry: { protocol: 'HTTP/1.1', status: 200, observatoryScore: 'F' },
        },
        {
          id: 'agent_network',
          name: 'NETWORK_WORKER',
          role: 'Analizador de Tráfico, Latencia y Eficiencia de Recursos',
          status: 'completed',
          executionTimeMs: 910,
          forksCount: 12,
          findingsCount: 3,
          tasksCompleted: ['Medición TTFB', 'Inspección de Headers de Compresión', 'Inventario de 34 recursos descargados'],
          telemetry: { ttfb: '1,840 ms', payload: '4.6 MB', compression: 'none' },
        },
        {
          id: 'agent_dom',
          name: 'DOM_EXPLORER',
          role: 'Auditor de Estructura HTML y Fingerprinting Wappalyzer',
          status: 'completed',
          executionTimeMs: 840,
          forksCount: 14,
          findingsCount: 2,
          tasksCompleted: ['Extracción de 1,840 nodos DOM', 'Detección de 14 tablas estructurales', 'Identificación de 2 tecnologías Wappalyzer'],
          telemetry: { domNodes: 1840, maxDepth: 18, technologies: 2 },
        },
        {
          id: 'agent_cro',
          name: 'CRO_RESEARCHER',
          role: 'Evaluador de Embudo, Jerarquía Visual y Fricción de Conversión',
          status: 'completed',
          executionTimeMs: 760,
          forksCount: 8,
          findingsCount: 4,
          tasksCompleted: ['Escaneo de CTAs de alta intención', 'Búsqueda de API WhatsApp', 'Auditoría de jerarquía de encabezados'],
          telemetry: { ctaCount: 2, whatsApp: 'Ausente', h1Count: 3 },
        },
        {
          id: 'agent_quote',
          name: 'QUOTE_ENGINE',
          role: 'Sintetizador de Propuesta Técnica y Cronograma',
          status: 'completed',
          executionTimeMs: 310,
          forksCount: 6,
          findingsCount: 6,
          tasksCompleted: ['Selección de Paquete Rediseño Pro', 'Desglose de entregables y horas estimadas', 'Armado de roadmap 12 días'],
          telemetry: { package: 'Rediseño Pro', totalHours: '79 hrs', timeline: '12 días' },
        },
      ],
      logs: [
        { id: 'l1', timestamp: '13:20:01.102', level: 'agent', agent: 'ORCHESTRATOR', message: 'Inicializando sesión para https://hotel-colonial-suites-demo.example.com', detail: 'DNS resuelto -> IP 198.51.100.42 (Apache/2.2 en Hostinger)' },
        { id: 'l2', timestamp: '13:20:01.189', level: 'info', agent: 'ORCHESTRATOR', message: 'Título extraído: "Hotel Colonial & Suites | Reservas, Tarifas y Alojamiento"', detail: 'Tag <title> capturado correctamente' },
        { id: 'l3', timestamp: '13:20:01.420', level: 'warn', agent: 'NETWORK_WORKER', message: 'TTFB crítico detectado: 1,840 ms superando umbral saludable (600 ms)', detail: 'Servidor respondió sin compresión gzip/brotli' },
        { id: 'l4', timestamp: '13:20:01.512', level: 'error', agent: 'DOM_EXPLORER', message: 'FALTA CRÍTICA: Etiqueta <meta name="viewport"> ausente en <head>', detail: 'Dispositivos móviles forzarán zoomout de 980px desktop' },
        { id: 'l5', timestamp: '13:20:01.603', level: 'error', agent: 'ORCHESTRATOR', message: 'Certificado SSL caducado hace 168 días (cPanel Authority)', detail: 'Grado Mozilla Observatory: F' },
        { id: 'l6', timestamp: '13:20:02.240', level: 'success', agent: 'QUOTE_ENGINE', message: 'Propuesta técnica generada: Paquete Rediseño Web Pro (6 módulos, 79 horas estimadas)', detail: 'Estimación de ROI esperada: +120% a +240%' },
      ],
    },
  },
  {
    id: 'dental_clinic',
    name: 'Clínica OdontoSalud',
    url: 'https://odontosalud-demo.example.com',
    category: 'Salud / Odontología',
    description: 'Posee botón de WhatsApp pero sin mensaje predeterminado codificado (?text= ausente), formulario sin labels accesibles y certificado Let\'s Encrypt válido en NGINX.',
    presetResult: {
      url: 'https://odontosalud-demo.example.com',
      pageTitle: 'Clínica Dental OdontoSalud - Odontología Integral e Implantes',
      scannedAt: new Date().toISOString(),
      status: 'success',
      auditDurationMs: 1120,
      totalForks: 32,
      scores: {
        overall: 56,
        performance: 62,
        tech: 58,
        cro: 50,
        security: 65,
        ratingLevel: 'Advertencia',
        colorHex: '#D29922',
      },
      issues: [
        {
          id: 'ISS-101',
          title: 'El botón de WhatsApp existe pero carece de un mensaje predeterminado codificado en la URL',
          category: 'cro',
          severity: 'warning',
          impactScore: 12,
          description: "El canal de WhatsApp fue detectado (https://wa.me/5491123456789), pero la URL no contiene el parámetro '?text='. El paciente es dirigido a un chat en blanco y debe pensar cómo iniciar la consulta, reduciendo la tasa de contacto.",
          evidence: "Parámetro ?text= ausente en https://wa.me/5491123456789",
          recommendation: "Añadir parámetro codificado en la URL (?text=Hola,%20quisiera%20agendar%20una%20cita...) para facilitar el primer paso.",
        },
        {
          id: 'ISS-102',
          title: 'Formulario de contacto carece de etiquetas <label> explícitas (3 campos)',
          category: 'cro',
          severity: 'warning',
          impactScore: 10,
          description: "El formulario 'form_citas' contiene 3 campos <input> ('paciente_nombre', 'telefono', 'servicio_interes') sin etiquetas <label> explícitas ni atributos 'aria-label', impidiendo la accesibilidad y el autocompletado en móviles.",
          evidence: "3 campos de formulario sin etiqueta <label>",
          recommendation: "Asociar cada campo con una etiqueta <label for='id'> explícita para cumplir con estándares WCAG.",
        },
        {
          id: 'ISS-103',
          title: 'Tiempo de primer byte (TTFB) moderado: 780 ms',
          category: 'performance',
          severity: 'warning',
          impactScore: 10,
          description: 'El TTFB supera los 600ms recomendados para experiencias fluidas en teléfonos móviles.',
          evidence: 'TTFB medido: 780ms',
          recommendation: 'Habilitar micro-caché FastCGI en NGINX y optimizar consultas MySQL.',
        },
      ],
      performance: {
        ttfbMs: 780,
        totalLoadTimeMs: 1850,
        htmlSizeBytes: 76000,
        estimatedAssetCount: 22,
        scriptsCount: 5,
        stylesCount: 4,
        imagesCount: 12,
        iframesCount: 1,
        domNodesTotal: 890,
        maxDomDepth: 12,
        compressionType: 'gzip',
        sslEnabled: true,
        hstsEnabled: true,
        mixedContentDetected: false,
        uncompressedImagesCount: 6,
        blockingScriptsCount: 2,
        networkInfrastructure: {
          ipAddresses: ['192.0.2.115'],
          ipv4: ['192.0.2.115'],
          ipv6: [],
          hostname: 'odontosalud-demo.example.com',
          detectedServer: 'nginx/1.18.0 (Ubuntu)',
          hostingProviderOrCdn: 'DigitalOcean Droplet (Ubuntu NGINX)',
          dnsLookupTimeMs: 68,
        },
      },
      techStack: {
        detected: [
          {
            name: 'WordPress',
            category: 'CMS',
            version: '6.2',
            description: 'Sistema de gestión de contenidos de código abierto para portales médicos.',
            website: 'https://wordpress.org',
            isObsolete: false,
          },
          {
            name: 'NGINX',
            category: 'Web Server',
            version: '1.18.0',
            description: 'Servidor web HTTP de alto rendimiento y proxy inverso.',
            website: 'https://nginx.org',
            isObsolete: false,
          },
        ],
        hasResponsiveViewport: true,
        viewportContent: 'width=device-width, initial-scale=1',
        usesTablesForLayout: false,
        tableLayoutCount: 0,
        usesIframesForLayout: false,
        iframeCount: 1,
        legacyJqueryDetected: false,
        deprecatedHtmlTags: [],
        htmlDoctype: '<!DOCTYPE html>',
      },
      securitySummary: {
        observatoryScore: 'B',
        missingHeaders: ['Content-Security-Policy (CSP)'],
        sslCertificate: {
          issuer: "Let's Encrypt Authority X3 (R3)",
          subject: 'odontosalud-demo.example.com',
          validFrom: '2026-08-01T00:00:00.000Z',
          validTo: '2026-11-01T23:59:59.000Z',
          daysRemaining: 30,
          signatureAlgorithm: 'sha256WithRSAEncryption',
          protocol: 'TLSv1.3',
          cipher: 'TLS_AES_256_GCM_SHA384',
          isExpired: false,
          isValid: true,
          serialNumber: '04:7A:B2:91:DE:33:AA',
        },
        vulnerabilities: [
          {
            id: 'SEC-HDR-CSP',
            source: 'Mozilla Observatory',
            name: 'Content-Security-Policy omitida',
            component: 'HTTP Response Headers',
            severity: 'Bajo',
            summary: 'Sin cabecera CSP estricta para control de fuentes de scripts.',
            recommendation: 'Definir directiva default-src y script-src en NGINX.',
          },
        ],
        totalVulnCount: 1,
      },
      cro: {
        ctaCount: 4,
        ctas: [
          { text: 'Solicitar Turno', href: '#contacto', tagName: 'BUTTON', isHighIntent: true },
          { text: 'Escríbenos por WhatsApp', href: 'https://wa.me/5491123456789', tagName: 'A', isHighIntent: true },
        ],
        hasWhatsApp: true,
        whatsAppLinks: ['https://wa.me/5491123456789'],
        whatsAppDetails: {
          detected: true,
          type: 'direct_link',
          rawLinkOrSelector: 'https://wa.me/5491123456789',
          hasPredefinedMessage: false,
          phoneNumber: '5491123456789',
          diagnosisNote: "El botón de WhatsApp existe pero carece de un mensaje predeterminado codificado en la URL (parámetro '?text=' ausente), obligando al prospecto a redactar la consulta desde cero y reduciendo la conversión un 35%.",
        },
        hasPhoneLink: true,
        phoneLinks: ['tel:+5491123456789'],
        hasContactForm: true,
        formCount: 1,
        formFieldIssues: [
          "El formulario 'form_citas' contiene 3 campos sin etiquetas <label> explícitas ni atributos 'aria-label' (<input name=\"paciente_nombre\">, <input name=\"telefono\">, <select name=\"servicio_interes\">), impidiendo la accesibilidad y el autocompletado en móviles.",
        ],
        headingHierarchy: [
          { tag: 'h1', text: 'Clínica Dental OdontoSalud - Cuidado Odontológico Especializado', level: 1 },
          { tag: 'h2', text: 'Nuestros Tratamientos Odontológicos', level: 2 },
          { tag: 'h3', text: 'Ortodoncia Invisible', level: 3 },
          { tag: 'h3', text: 'Implantes Dentales Inmediatos', level: 3 },
        ],
        h1Count: 1,
        h1Texts: ['Clínica Dental OdontoSalud - Cuidado Odontológico Especializado'],
        hasSingleH1: true,
        headingIssues: [],
        croFindings: [
          'Estructura <h1> óptima y singular: Declarado como "Clínica Dental OdontoSalud - Cuidado Odontológico Especializado".',
          "El botón de WhatsApp existe pero carece de un mensaje predeterminado codificado en la URL (parámetro '?text=' ausente), obligando al prospecto a redactar la consulta desde cero y reduciendo la conversión un 35%.",
          "El formulario 'form_citas' contiene 3 campos sin etiquetas <label> explícitas ni atributos 'aria-label', impidiendo la accesibilidad y el autocompletado en móviles.",
          'Llamadas a la acción (CTAs) detectadas: 4 botones/enlaces de acción ("Solicitar Turno", "Escríbenos por WhatsApp").',
        ],
        wordCount: 860,
        totalImages: 12,
        imagesMissingAlt: 4,
        hasSocialProof: true,
        hasLegalPrivacyLink: true,
      },
      quote: {
        tierId: 'express_landing',
        tierName: 'Sprint Express CRO & Optimización de Citas',
        tagline: 'Corrección inmediata del embudo de agendamiento de pacientes y optimización de conversión móvil.',
        summary: 'Configuración de mensaje inteligente para WhatsApp, resolución de labels en formulario de reserva, compresión de imágenes médicas a WebP y aceleración de TTFB en servidor NGINX.',
        estimatedDeliveryDays: 6,
        estimatedConversionUplift: '+45% a +80% en solicitudes de turno',
        totalEstimatedHours: 26,
        lineItems: [
          {
            id: 'mod_wa_prescript',
            title: 'Configuración de Mensaje Predeterminado en WhatsApp y Flujo Rápido',
            category: 'cro',
            triggerReason: "Botón de WhatsApp activo sin parámetro '?text=' codificado",
            estimatedHours: 4,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Permite al paciente enviar su solicitud en un solo toque sin escribir desde cero.',
            clientBenefit: 'Aumento inmediato en la tasa de pacientes que completan el primer mensaje.',
          },
          {
            id: 'mod_form_wcag',
            title: 'Accesibilidad WCAG y Labels Nativos en Formulario de Turnos',
            category: 'cro',
            triggerReason: 'Campos de formulario sin etiquetas <label> explícitas',
            estimatedHours: 6,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Activa el llenado automático de nombres y teléfonos en teclados móviles.',
            clientBenefit: 'Reduce a la mitad el tiempo necesario para enviar una solicitud de turno.',
          },
          {
            id: 'mod_nginx_ttfb',
            title: 'Aceleración FastCGI y Compresión WebP en Servidor NGINX',
            category: 'perf',
            triggerReason: 'TTFB de 780ms y 6 imágenes pesadas sin formato moderno',
            estimatedHours: 8,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Optimiza la entrega de datos para que la web cargue en menos de 1 segundo.',
            clientBenefit: 'Mejor posición en Google y menor abandono de pacientes.',
          },
        ],
        actionRoadmap: [
          { phase: 'Fase 1', title: 'Ajuste de Formulario & WhatsApp', duration: 'Días 1 - 3', tasks: ['Mensajes predeterminados', 'Asociación de labels WCAG'] },
          { phase: 'Fase 2', title: 'Optimización Servidor NGINX', duration: 'Días 4 - 6', tasks: ['Caché FastCGI', 'Conversión a WebP y entrega'] },
        ],
      },
      subagents: [
        {
          id: 'agent_orchestrator',
          name: 'ORCHESTRATOR_AGENT',
          role: 'Controlador Maestro de Auditoría',
          status: 'completed',
          executionTimeMs: 1120,
          forksCount: 3,
          findingsCount: 3,
          tasksCompleted: [
            'DNS resuelto: 192.0.2.115',
            'Certificado Let\'s Encrypt TLS 1.3 verificado',
            'Título extraído: "Clínica Dental OdontoSalud"',
          ],
          telemetry: { protocol: 'HTTP/2', status: 200, observatoryScore: 'B' },
        },
      ],
      logs: [
        { id: 'ld1', timestamp: '13:21:00.040', level: 'agent', agent: 'ORCHESTRATOR', message: 'Iniciando escaneo para https://odontosalud-demo.example.com', detail: 'DNS resuelto: 192.0.2.115 en DigitalOcean NGINX' },
        { id: 'ld2', timestamp: '13:21:00.120', level: 'info', agent: 'NETWORK_WORKER', message: 'Certificado SSL válido emitido por Let\'s Encrypt (vence en 30 días)', detail: 'Protocolo TLSv1.3 activo' },
        { id: 'ld3', timestamp: '13:21:00.340', level: 'warn', agent: 'CRO_RESEARCHER', message: 'WhatsApp detectado pero falta mensaje codificado (?text= ausente)', detail: 'Enlace analizado: https://wa.me/5491123456789' },
        { id: 'ld4', timestamp: '13:21:00.410', level: 'warn', agent: 'CRO_RESEARCHER', message: 'Formulario de citas contiene 3 campos sin <label> explícito', detail: 'Afecta accesibilidad en smartphones' },
      ],
    },
  },
  {
    id: 'saas_modern',
    name: 'Acrobatix Cloud OS',
    url: 'https://acrobatix-cloud.example.com',
    category: 'Software / B2B SaaS',
    description: 'Stack moderno (React/Next.js), alta velocidad (TTFB 190ms), Cloudflare Edge CDN con TLS 1.3 ECC, y widget de chat integrado.',
    presetResult: {
      url: 'https://acrobatix-cloud.example.com',
      pageTitle: 'Acrobatix Cloud OS - Enterprise Cloud Platform for Modern Engineering',
      scannedAt: new Date().toISOString(),
      status: 'success',
      auditDurationMs: 980,
      totalForks: 26,
      scores: {
        overall: 86,
        performance: 92,
        tech: 94,
        cro: 76,
        security: 88,
        ratingLevel: 'Bueno',
        colorHex: '#56D4DD',
      },
      issues: [
        {
          id: 'ISS-201',
          title: 'Falta canal conversacional directo para compradores Enterprise',
          category: 'cro',
          severity: 'warning',
          impactScore: 12,
          description: 'Solo ofrece registro de autoservicio o formulario formal de contacto. En software B2B, un agendador en tiempo real incrementa demos en +40%.',
          evidence: 'Sin agendador directo de reuniones en el hero section',
          recommendation: 'Integrar widget de agenda instantánea para equipos comerciales.',
        },
      ],
      performance: {
        ttfbMs: 190,
        totalLoadTimeMs: 920,
        htmlSizeBytes: 32000,
        estimatedAssetCount: 18,
        scriptsCount: 5,
        stylesCount: 2,
        imagesCount: 8,
        iframesCount: 0,
        domNodesTotal: 620,
        maxDomDepth: 9,
        compressionType: 'br',
        sslEnabled: true,
        hstsEnabled: true,
        mixedContentDetected: false,
        uncompressedImagesCount: 0,
        blockingScriptsCount: 0,
        networkInfrastructure: {
          ipAddresses: ['104.21.32.88', '172.67.180.12', '2606:4700:3033::6815:2058'],
          ipv4: ['104.21.32.88', '172.67.180.12'],
          ipv6: ['2606:4700:3033::6815:2058'],
          hostname: 'acrobatix-cloud.example.com',
          detectedServer: 'cloudflare',
          hostingProviderOrCdn: 'Cloudflare Edge CDN & Anti-DDoS Global',
          dnsLookupTimeMs: 24,
        },
      },
      techStack: {
        detected: [
          {
            name: 'Next.js',
            category: 'JavaScript Framework',
            description: 'Framework de React para aplicaciones web con renderizado del lado del servidor (SSR).',
            website: 'https://nextjs.org',
            isObsolete: false,
          },
          {
            name: 'React',
            category: 'JavaScript Framework',
            description: 'Biblioteca frontend de JavaScript desarrollada por Meta para construir interfaces de usuario.',
            website: 'https://react.dev',
            isObsolete: false,
          },
          {
            name: 'Tailwind CSS',
            category: 'CSS Framework',
            description: 'Framework CSS orientado a utilidades para diseño rápido de interfaces modernas.',
            website: 'https://tailwindcss.com',
            isObsolete: false,
          },
          {
            name: 'Cloudflare',
            category: 'Security / CDN',
            description: 'Red global de entrega de contenidos (CDN) y mitigación DDoS en el Edge.',
            website: 'https://cloudflare.com',
            isObsolete: false,
          },
        ],
        hasResponsiveViewport: true,
        viewportContent: 'width=device-width, initial-scale=1',
        usesTablesForLayout: false,
        tableLayoutCount: 0,
        usesIframesForLayout: false,
        iframeCount: 0,
        legacyJqueryDetected: false,
        deprecatedHtmlTags: [],
        htmlDoctype: '<!DOCTYPE html>',
      },
      securitySummary: {
        observatoryScore: 'A',
        missingHeaders: ['Content-Security-Policy (CSP)'],
        sslCertificate: {
          issuer: 'Cloudflare Inc ECC CA-3',
          subject: 'acrobatix-cloud.example.com',
          validFrom: '2026-05-10T00:00:00.000Z',
          validTo: '2027-05-10T23:59:59.000Z',
          daysRemaining: 220,
          signatureAlgorithm: 'ecdsa-with-SHA384',
          protocol: 'TLSv1.3',
          cipher: 'TLS_AES_256_GCM_SHA384',
          isExpired: false,
          isValid: true,
          serialNumber: '0E:88:1C:44:00:BF:91',
        },
        vulnerabilities: [
          {
            id: 'SEC-HDR-CSP',
            source: 'Mozilla Observatory',
            name: 'Política CSP pendiente de refinamiento',
            component: 'HTTP Response Headers',
            severity: 'Bajo',
            summary: 'Se recomienda agregar Content-Security-Policy restrictivo para mitigar scripts de terceros.',
            recommendation: 'Definir directiva frame-ancestors y script-src en la cabecera.',
          },
        ],
        totalVulnCount: 1,
      },
      cro: {
        ctaCount: 6,
        ctas: [
          { text: 'Comenzar Prueba Gratis', href: '/signup', tagName: 'BUTTON', isHighIntent: true },
          { text: 'Ver Demostración', href: '/demo', tagName: 'A', isHighIntent: true },
        ],
        hasWhatsApp: true,
        whatsAppLinks: ['https://wa.me/18005550199?text=Hola,%20quisiera%20una%20demostracion%20de%20Acrobatix'],
        whatsAppDetails: {
          detected: true,
          type: 'floating_widget',
          widgetName: 'JoinChat Enterprise Floating Widget',
          rawLinkOrSelector: 'Selector CSS ".joinchat" (Widget activo)',
          hasPredefinedMessage: true,
          predefinedMessageContent: 'Hola, quisiera una demostracion de Acrobatix',
          phoneNumber: '18005550199',
          diagnosisNote: 'El botón de WhatsApp cuenta con mensaje predeterminado codificado: "Hola, quisiera una demostracion de Acrobatix", facilitando el inicio de la conversación sin fricción.',
        },
        hasPhoneLink: false,
        phoneLinks: [],
        hasContactForm: true,
        formCount: 1,
        formFieldIssues: [],
        headingHierarchy: [
          { tag: 'h1', text: 'La plataforma en la nube para equipos que escalan', level: 1 },
          { tag: 'h2', text: 'Características Principales', level: 2 },
          { tag: 'h2', text: 'Casos de Éxito', level: 2 },
        ],
        h1Count: 1,
        h1Texts: ['La plataforma en la nube para equipos que escalan'],
        hasSingleH1: true,
        headingIssues: [],
        croFindings: [
          'Estructura <h1> óptima y singular: Declarado como "La plataforma en la nube para equipos que escalan".',
          'El botón de WhatsApp cuenta con mensaje predeterminado codificado: "Hola, quisiera una demostracion de Acrobatix", facilitando el inicio de la conversación sin fricción.',
          'Formularios de contacto: Se inspeccionaron 1 formulario(s) con etiquetas <label> y accesibilidad verificada.',
          'Llamadas a la acción (CTAs) detectadas: 6 botones/enlaces de acción ("Comenzar Prueba Gratis", "Ver Demostración").',
        ],
        wordCount: 1420,
        totalImages: 8,
        imagesMissingAlt: 3,
        hasSocialProof: true,
        hasLegalPrivacyLink: true,
      },
      quote: {
        tierId: 'enterprise_lead_engine',
        tierName: 'Optimización B2B & Lead Conversion Engine',
        tagline: 'Refinamiento de embudo para maximizar demos comerciales y captación de cuentas enterprise.',
        summary: 'Incorporación de agendador interactivo de videollamadas, calculadora interactiva de ROI para clientes potenciales y enriquecimiento de testimonios para duplicar cierres corporativos.',
        estimatedDeliveryDays: 8,
        estimatedConversionUplift: '+38% en agendamiento de demos',
        totalEstimatedHours: 36,
        lineItems: [
          {
            id: 'mod_cal_scheduler',
            title: 'Integración de Agendador Interactivo de Demos en Tiempo Real',
            category: 'cro',
            triggerReason: 'Proceso de contacto actual genera fricción en compradores calificados',
            estimatedHours: 10,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Permite a prospectos calificados agendar llamadas directamente en el calendario del equipo.',
            clientBenefit: 'Aumenta en +40% la asistencia a reuniones comerciales.',
          },
          {
            id: 'mod_roi_calc',
            title: 'Calculadora Interactiva de Ahorro y ROI para Cuentas B2B',
            category: 'cro',
            triggerReason: 'Aumentar la persuasión de valor financiero en landing de precios',
            estimatedHours: 14,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'Muestra con números concretos cuánto dinero ahorra el cliente al contratarte.',
            clientBenefit: 'Justifica el valor de la propuesta de forma matemática y convincente.',
          },
          {
            id: 'mod_alt_accessibility',
            title: 'Optimización de Accesibilidad y Metadatos de Producto',
            category: 'seo',
            triggerReason: 'Imágenes clave de producto sin atributos de texto alternativo',
            estimatedHours: 4,
            selected: true,
            isCore: false,
            plainWhyNeeded: 'Mejora la indexación de imágenes en motores de búsqueda.',
            clientBenefit: 'Tráfico de búsqueda cualificado y cumplimiento de estándares web.',
          },
          {
            id: 'mod_social_proof_interactive',
            title: 'Carrusel de Casos de Estudio con Métricas Cuantitativas Verificadas',
            category: 'cro',
            triggerReason: 'Refuerzo de prueba social antes del formulario de precios',
            estimatedHours: 8,
            selected: true,
            isCore: true,
            plainWhyNeeded: 'La prueba social disminuye las dudas antes de tomar la decisión final.',
            clientBenefit: 'Genera autoridad y reduce el ciclo de venta.',
          },
        ],
        actionRoadmap: [
          { phase: 'Fase 1', title: 'Diseño de Calculadora & Agendador', duration: 'Días 1 - 3', tasks: ['Lógica financiera de retorno', 'Integración con Google Calendar/CRM'] },
          { phase: 'Fase 2', title: 'Despliegue y A/B Testing', duration: 'Días 4 - 8', tasks: ['Pruebas de tracking de conversión', 'Lanzamiento controlado'] },
        ],
      },
      subagents: [
        {
          id: 'agent_orchestrator',
          name: 'ORCHESTRATOR_AGENT',
          role: 'Controlador Maestro de Auditoría',
          status: 'completed',
          executionTimeMs: 980,
          forksCount: 2,
          findingsCount: 1,
          tasksCompleted: [
            'DNS verificado: Cloudflare Anycast IPs (104.21.32.88 / 172.67.180.12)',
            'Certificado Cloudflare ECC TLS 1.3 verificado',
            'Título extraído: "Acrobatix Cloud OS - Enterprise Cloud Platform"',
          ],
          telemetry: { protocol: 'HTTP/3', status: 200, observatoryScore: 'A' },
        },
      ],
      logs: [
        { id: 'ls1', timestamp: '13:22:00.012', level: 'agent', agent: 'ORCHESTRATOR', message: 'Iniciando análisis de alto rendimiento para https://acrobatix-cloud.example.com', detail: 'Edge CDN detectado: Cloudflare' },
        { id: 'ls2', timestamp: '13:22:00.201', level: 'success', agent: 'NETWORK_WORKER', message: 'Excelente TTFB: 190 ms con compresión Brotli', detail: 'Assets cacheados correctamente' },
        { id: 'ls3', timestamp: '13:22:00.410', level: 'info', agent: 'DOM_EXPLORER', message: 'Stack moderno: Next.js + React + Tailwind CSS identificado por Wappalyzer', detail: 'Sin librerías obsoletas' },
        { id: 'ls4', timestamp: '13:22:00.780', level: 'success', agent: 'QUOTE_ENGINE', message: 'Propuesta técnica B2B lista (36 horas estimadas, 8 días de entrega)', detail: 'Enfocada en agendador interactivo de demos' },
      ],
    },
  },
];
